# MenuMoose Configuration

# Recipients for weekly menu email
# Format: comma-separated email addresses
recipients:
  - qiang.1.huang@nokia.com
  # - jiao.wang@nokia.com
  # - lingyan.jiang@nokia.com
  # - qiuxiang.yang@nokia.com
  # - tuanbin.liu@nokia.com
  # - zhong.1.zhuang@nokia.com
  # - yang.deng@nokia.com
  # - grace.guo@nokia.com
  - rendy.huang@me.com

recipients_test:
  - qiang.1.huang@nokia.com
  - rendy.huang@me.com

# Sodexo Menu API URL
menu_url: "https://www.sodexo.fi/ruokalistat/output/weekly_json/3207223"

# Translation settings
translation:
  # model: "stepfun/step-3.5-flash:free"  # or "gpt-4o-mini" for OpenAI
  model: "deepseek-v4-pro"
  api_base: "https://api.deepseek.com"
   # api_key comes from GitHub Secrets

# Menu details
restaurant:
  name: "Nokia Linnanmaa Oulu"
  url: "https://www.sodexo.fi/ravintolat/nokia-linnanmaa"

resend_from_email: "MenuMoose🫎 <noreply@panda-tech.top>"
